name: CD

on:
  push:
    branches:
      - main

jobs:
  buildTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: buildTest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Deploy
        run: yarn run deploy

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: buildTest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Install dependencies
        run: yarn install
      - name: Release
        run: yarn run release
      - name: Push Tags
        run: git push --follow-tags origin main
